### PR TITLE
Update the deep-histopath to be latest

### PR DESCRIPTION
**Pull request by feihugis**
The old version of deep-histopath repo will not work with TF-1.12.2 due to the API change in Keras: `ImportError: cannot import name 'get_source_inputs'`. The latest deep-histopath could work with TF-1.12.2, so we can remove `git check ......`.   With this PR merged, we can merge #24.

### CODE REVIEW

**Comment by feihugis** [comment]
I think the checks will not pass until we update the TF version.

File: Dockerfile [hunk 1]
```diff
@@ -16,7 +16,6 @@ RUN pip install -r requirements.txt
 RUN cd /workspace && \
     git clone https://github.com/codait/deep-histopath && \
     cd deep-histopath && \
-    git checkout e0c93c3543830a0ee07ad9408e844465f045781c && \
```
Comment (bdwyer2) [inline Dockerfile]: I like the idea of locking this to a specific commit or maybe a release so that a changed to the deep histopath master branch doesn't break this model. Maybe you can just change this to the current latest commit?

Comment (feihugis) [reply Dockerfile]: Yeah, that is a good idea. I just revert it and update the commit id.
